### PR TITLE
Update npblacklist.json

### PR DESCRIPTION
**Pull request by xChillphil**
Changes proposed by xChillphil

### CODE REVIEW

**Comment by xChillphil** [comment]
Hey there, added three of our world maps for Club Ancients

**Comment by cyberkitsune** [comment]
Hey! Thanks for contributing. If you could though, could you add commas after each of your entries except the last one? The tests won't pass otherwise, sadly. (See the lines above as an example)

**Comment by xChillphil** [comment]
Thanks, my bad. Should be fixed now

**Comment by cyberkitsune** [comment]
Awesome, all checks passing now. Thanks!

**Pull request merged**
